application:
  name: Dashboard IMU
  environment: development
  database:
    host: localhost
    name: dashboard-imu
    username: postgres
    password: 1
    port: 5432
  backend:
    port: 8700
  socket:
    port: 8701
  mqtt:
    port: 8702